name: CI Pipeline - Build & Push Docker

on:
  push:
    branches:
      - docker_ci

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run training script
        run: |
          python src/train.py

      - name: Build Docker Image
        run: |
          docker build -t housing-model .

      - name: Run Docker Container to Test Predict
        run: |
          docker run --rm housing-model

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Docker Image to DockerHub
        run: |
          docker tag housing-model pranav1114/housing-predictor:latest
          docker push pranav1114/housing-predictor:latest

